// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/redis"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelDayStatisFieldNames          = builder.RawFieldNames(&ChannelDayStatis{})
	channelDayStatisRows                = strings.Join(channelDayStatisFieldNames, ",")
	channelDayStatisRowsExpectAutoSet   = strings.Join(stringx.Remove(channelDayStatisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelDayStatisRowsWithPlaceHolder = strings.Join(stringx.Remove(channelDayStatisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheChannelDayStatisIdPrefix                         = "cache:channelDayStatis:id:"
	cacheChannelDayStatisRecordDateClientIdCurrencyPrefix = "cache:channelDayStatis:recordDate:clientId:currency:"
)

type (
	channelDayStatisModel interface {
		Insert(ctx context.Context, data *ChannelDayStatis) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChannelDayStatis, error)
		FindOneByRecordDateClientIdCurrency(ctx context.Context, recordDate int64, clientId int64, currency string) (*ChannelDayStatis, error)
		Update(ctx context.Context, data *ChannelDayStatis) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChannelDayStatisModel struct {
		sqlc.CachedConn
		table string
	}

	ChannelDayStatis struct {
		Id                   int64     `db:"id"`
		ClientId             int64     `db:"client_id"`                // 渠道id
		GameName             string    `db:"game_name"`                // 游戏名称
		Currency             string    `db:"currency"`                 // 货币代码
		PlayerNum            int64     `db:"player_num"`               // 总游戏人次
		TotalPlayerNum       int64     `db:"total_player_num"`         // 总游戏人数，基于投注订单去重的会员人数
		PlayNum              int64     `db:"play_num"`                 // 总局数=当前进行的所有有效局数
		PreBetAmt            float64   `db:"pre_bet_amt"`              // 游戏前下注金额=当天所有局数的游戏前下注之和
		PreCashoutAmt        float64   `db:"pre_cashout_amt"`          // 游戏前兑现金额=当天所有局数的游戏前下注的中奖金额之和
		IngBetAmt            float64   `db:"ing_bet_amt"`              // 游戏中下注金额=当天所有局数的游戏中下注之和
		IngCashoutAmt        float64   `db:"ing_cashout_amt"`          // 游戏中兑现金额=当天所有局数的游戏中下注的中奖金额之和
		FeeAmt               float64   `db:"fee_amt"`                  // 总服务费
		TotalBetAmt          float64   `db:"total_bet_amt"`            // 玩家总下注=当天所有局数的总下注之和
		TotalValidBetAmt     float64   `db:"total_valid_bet_amt"`      // 总有效投注金额，因有取消投注，所以统计真实的投注
		PrizePoolAddAmt      float64   `db:"prize_pool_add_amt"`       // 奖池增加金额，统计奖池新增的金额
		PrizePoolPayoutAmt   float64   `db:"prize_pool_payout_amt"`    // 奖池派发金额，统计奖池派发出去的金额
		PrizePoolValidBetAmt float64   `db:"prize_pool_valid_bet_amt"` // 奖池有效投注金额=总现有奖池-奖池派发金额
		PrizePoolRate        int64     `db:"prize_pool_rate"`          // 奖池率=总盈亏/总有效投注金额*100，总有效投注=0时，显示固定文案
		TotalBonus           float64   `db:"total_bonus"`              // 总返奖金额=当天所有局数的总中奖金额之和
		BonusRate            int64     `db:"bonus_rate"`               // 返奖率=总中奖金额/玩家总下注  存储值=返奖率*10000
		MatchBetPlayerNum    int64     `db:"match_bet_player_num"`     // 赛事投注人数，统计参与赛事盘口的用户人次数（不去重）
		MatchValidBetAmt     float64   `db:"match_valid_bet_amt"`      // 赛事有效投注金额
		MatchProfitAmt       float64   `db:"match_profit_amt"`         // 赛事总盈亏
		MatchKillRate        int64     `db:"match_kill_rate"`          // 赛事投注杀率
		RollingBetPlayerNum  int64     `db:"rolling_bet_player_num"`   // 滚盘投注人数，统计参与滚盘的用户人次数（不去重）
		RollingValidBetAmt   float64   `db:"rolling_valid_bet_amt"`    // 滚盘有效投注金额
		RollingProfitAmt     float64   `db:"rolling_profit_amt"`       // 滚盘总盈亏
		RollingKillRate      int64     `db:"rolling_kill_rate"`        // 滚盘投注杀率
		TotalProfitAmt       float64   `db:"total_profit_amt"`         // 总盈亏=总投注-总兑现
		TotalKillRate        int64     `db:"total_kill_rate"`          // 总杀率=总盈亏/总有效投注*100
		OneNum               int64     `db:"one_num"`                  // 当天所有局数中倍数结果为1的局数
		TwoNum               int64     `db:"two_num"`                  // 当天所有局数中倍数结果在(1,2)的局数
		FiveNum              int64     `db:"five_num"`                 // 当天所有局数中倍数结果在[2,5)的局数
		TenNum               int64     `db:"ten_num"`                  // 当天所有局数中倍数结果在[5~10)的局数
		TenMoreNum           int64     `db:"ten_more_num"`             // 当天所有局数中倍数结果在[10,MAX]的局数
		RecordDate           int64     `db:"record_date"`              // 数据归属日期 格式：YYYYMMDD ，如：20240531
		CreateTime           time.Time `db:"create_time"`              // 数据创建时间
	}
)

func newChannelDayStatisModel(conn sqlx.SqlConn, rds *redis.Redis) *defaultChannelDayStatisModel {
	return &defaultChannelDayStatisModel{
		CachedConn: sqlc.NewNodeConn(conn, rds),
		table:      "`channel_day_statis`",
	}
}

func (m *defaultChannelDayStatisModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	channelDayStatisIdKey := fmt.Sprintf("%s%v", cacheChannelDayStatisIdPrefix, id)
	channelDayStatisRecordDateClientIdCurrencyKey := fmt.Sprintf("%s%v:%v:%v", cacheChannelDayStatisRecordDateClientIdCurrencyPrefix, data.RecordDate, data.ClientId, data.Currency)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, channelDayStatisIdKey, channelDayStatisRecordDateClientIdCurrencyKey)
	return err
}

func (m *defaultChannelDayStatisModel) FindOne(ctx context.Context, id int64) (*ChannelDayStatis, error) {
	channelDayStatisIdKey := fmt.Sprintf("%s%v", cacheChannelDayStatisIdPrefix, id)
	var resp ChannelDayStatis
	err := m.QueryRowCtx(ctx, &resp, channelDayStatisIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelDayStatisRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelDayStatisModel) FindOneByRecordDateClientIdCurrency(ctx context.Context, recordDate int64, clientId int64, currency string) (*ChannelDayStatis, error) {
	channelDayStatisRecordDateClientIdCurrencyKey := fmt.Sprintf("%s%v:%v:%v", cacheChannelDayStatisRecordDateClientIdCurrencyPrefix, recordDate, clientId, currency)
	var resp ChannelDayStatis
	err := m.QueryRowIndexCtx(ctx, &resp, channelDayStatisRecordDateClientIdCurrencyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `record_date` = ? and `client_id` = ? and `currency` = ? limit 1", channelDayStatisRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, recordDate, clientId, currency); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelDayStatisModel) Insert(ctx context.Context, data *ChannelDayStatis) (sql.Result, error) {
	channelDayStatisIdKey := fmt.Sprintf("%s%v", cacheChannelDayStatisIdPrefix, data.Id)
	channelDayStatisRecordDateClientIdCurrencyKey := fmt.Sprintf("%s%v:%v:%v", cacheChannelDayStatisRecordDateClientIdCurrencyPrefix, data.RecordDate, data.ClientId, data.Currency)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, channelDayStatisRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClientId, data.GameName, data.Currency, data.PlayerNum, data.TotalPlayerNum, data.PlayNum, data.PreBetAmt, data.PreCashoutAmt, data.IngBetAmt, data.IngCashoutAmt, data.FeeAmt, data.TotalBetAmt, data.TotalValidBetAmt, data.PrizePoolAddAmt, data.PrizePoolPayoutAmt, data.PrizePoolValidBetAmt, data.PrizePoolRate, data.TotalBonus, data.BonusRate, data.MatchBetPlayerNum, data.MatchValidBetAmt, data.MatchProfitAmt, data.MatchKillRate, data.RollingBetPlayerNum, data.RollingValidBetAmt, data.RollingProfitAmt, data.RollingKillRate, data.TotalProfitAmt, data.TotalKillRate, data.OneNum, data.TwoNum, data.FiveNum, data.TenNum, data.TenMoreNum, data.RecordDate)
	}, channelDayStatisIdKey, channelDayStatisRecordDateClientIdCurrencyKey)
	return ret, err
}

func (m *defaultChannelDayStatisModel) Update(ctx context.Context, newData *ChannelDayStatis) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	channelDayStatisIdKey := fmt.Sprintf("%s%v", cacheChannelDayStatisIdPrefix, data.Id)
	channelDayStatisRecordDateClientIdCurrencyKey := fmt.Sprintf("%s%v:%v:%v", cacheChannelDayStatisRecordDateClientIdCurrencyPrefix, data.RecordDate, data.ClientId, data.Currency)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelDayStatisRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ClientId, newData.GameName, newData.Currency, newData.PlayerNum, newData.TotalPlayerNum, newData.PlayNum, newData.PreBetAmt, newData.PreCashoutAmt, newData.IngBetAmt, newData.IngCashoutAmt, newData.FeeAmt, newData.TotalBetAmt, newData.TotalValidBetAmt, newData.PrizePoolAddAmt, newData.PrizePoolPayoutAmt, newData.PrizePoolValidBetAmt, newData.PrizePoolRate, newData.TotalBonus, newData.BonusRate, newData.MatchBetPlayerNum, newData.MatchValidBetAmt, newData.MatchProfitAmt, newData.MatchKillRate, newData.RollingBetPlayerNum, newData.RollingValidBetAmt, newData.RollingProfitAmt, newData.RollingKillRate, newData.TotalProfitAmt, newData.TotalKillRate, newData.OneNum, newData.TwoNum, newData.FiveNum, newData.TenNum, newData.TenMoreNum, newData.RecordDate, newData.Id)
	}, channelDayStatisIdKey, channelDayStatisRecordDateClientIdCurrencyKey)
	return err
}

func (m *defaultChannelDayStatisModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheChannelDayStatisIdPrefix, primary)
}

func (m *defaultChannelDayStatisModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelDayStatisRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultChannelDayStatisModel) tableName() string {
	return m.table
}
