// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	gameDayStatisFieldNames          = builder.RawFieldNames(&GameDayStatis{})
	gameDayStatisRows                = strings.Join(gameDayStatisFieldNames, ",")
	gameDayStatisRowsExpectAutoSet   = strings.Join(stringx.Remove(gameDayStatisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameDayStatisRowsWithPlaceHolder = strings.Join(stringx.Remove(gameDayStatisFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameDayStatisModel interface {
		Insert(ctx context.Context, data *GameDayStatis) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameDayStatis, error)
		FindOneByTermIdRecordDate(ctx context.Context, channelID, termId int64, recordDate int64) (*GameDayStatis, error)
		Update(ctx context.Context, data *GameDayStatis) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameDayStatisModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameDayStatis struct {
		Id            int64           `db:"id"`
		ClientId      int64           `db:"client_id"`       // 渠道id
		GameName      string          `db:"game_name"`       // 游戏名称
		TermId        int64           `db:"term_id"`         // 每一局游戏的id
		PlayerNum     int64           `db:"player_num"`      // 单局参与游戏的总玩家数
		TotalBetAmt   decimal.Decimal `db:"total_bet_amt"`   // 单局的总下注金额
		GameResult    decimal.Decimal `db:"game_result"`     // 单局的倍数结果
		PreBetNum     int64           `db:"pre_bet_num"`     // 游戏前下注人次，游戏前下注的总玩家人次数
		IngBetNum     int64           `db:"ing_bet_num"`     // 游戏中下注人次，游戏中下注的总玩家人次数
		PreBetAmt     decimal.Decimal `db:"pre_bet_amt"`     // 游戏前下注的总投注金额
		IngBetAmt     decimal.Decimal `db:"ing_bet_amt"`     // 游戏中下注的总投注金额
		FeeAmt        decimal.Decimal `db:"fee_amt"`         // 游戏中下注的总服务费金额
		PreCashoutNum int64           `db:"pre_cashout_num"` // 游戏前下注的订单中兑现的人次数
		IngCashoutNum int64           `db:"ing_cashout_num"` // 游戏中下注的订单中兑现的人次数
		PreCashoutAmt decimal.Decimal `db:"pre_cashout_amt"` // 游戏前下注的订单中兑现的总金额
		IngCashoutAmt decimal.Decimal `db:"ing_cashout_amt"` // 游戏中下注的订单中兑现的总金额
		TotalBonus    decimal.Decimal `db:"total_bonus"`     // 兑现成功玩家的返奖总额
		BonusRate     int64           `db:"bonus_rate"`      // 单局返奖率=总中奖金额/玩家总下注
		CtrlStatus    int64           `db:"ctrl_status"`     // 控局状态 1=正常 2=控输 3=控赢
		RecordDate    int64           `db:"record_date"`     // 数据归属日期 格式：YYYYMMDD ，如：20240531
		CreateTime    time.Time       `db:"create_time"`     // 数据创建时间
		Currency      string          `db:"currency"`        // 币种，因为支持多币种投注，所以每条数据按币种统计
		// 新增字段
		TotalPlayerNum       int64           `db:"total_player_num"`         // 总游戏人数，基于投注订单去重的会员人数
		TotalValidBetAmt     decimal.Decimal `db:"total_valid_bet_amt"`      // 总有效投注金额，因有取消投注，所以统计真实的投注
		PrizePoolAddAmt      decimal.Decimal `db:"prize_pool_add_amt"`       // 奖池增加金额，统计奖池新增的金额
		PrizePoolPayoutAmt   decimal.Decimal `db:"prize_pool_payout_amt"`    // 奖池派发金额，统计奖池派发出去的金额
		PrizePoolValidBetAmt decimal.Decimal `db:"prize_pool_valid_bet_amt"` // 奖池有效投注金额=总现有奖池-奖池派发金额
		PrizePoolRate        int64           `db:"prize_pool_rate"`          // 奖池率=总盈亏/总有效投注金额*100，总有效投注=0时，显示固定文案
		MatchBetPlayerNum    int64           `db:"match_bet_player_num"`     // 赛事投注人数，统计参与赛事盘口的用户人次数（不去重）
		MatchValidBetAmt     decimal.Decimal `db:"match_valid_bet_amt"`      // 赛事有效投注金额
		MatchProfitAmt       decimal.Decimal `db:"match_profit_amt"`         // 赛事总盈亏
		MatchKillRate        int64           `db:"match_kill_rate"`          // 赛事投注杀率
		RollingBetPlayerNum  int64           `db:"rolling_bet_player_num"`   // 滚盘投注人数，统计参与滚盘的用户人次数（不去重）
		RollingValidBetAmt   decimal.Decimal `db:"rolling_valid_bet_amt"`    // 滚盘有效投注金额
		RollingProfitAmt     decimal.Decimal `db:"rolling_profit_amt"`       // 滚盘总盈亏
		RollingKillRate      int64           `db:"rolling_kill_rate"`        // 滚盘投注杀率
		TotalProfitAmt       decimal.Decimal `db:"total_profit_amt"`         // 总盈亏=总投注-总兑现
		TotalKillRate        int64           `db:"total_kill_rate"`          // 总杀率=总盈亏/总有效投注*100
	}
)

func newGameDayStatisModel(conn sqlx.SqlConn) *defaultGameDayStatisModel {
	return &defaultGameDayStatisModel{
		conn:  conn,
		table: "`game_day_statis`",
	}
}

func (m *defaultGameDayStatisModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameDayStatisModel) FindOne(ctx context.Context, id int64) (*GameDayStatis, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameDayStatisRows, m.table)
	var resp GameDayStatis
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameDayStatisModel) FindOneByTermIdRecordDate(ctx context.Context, channelID, termId int64, recordDate int64) (*GameDayStatis, error) {
	var resp GameDayStatis
	query := fmt.Sprintf("select %s from %s where `channel_id` = ? and `term_id` = ? and `record_date` = ? limit 1", gameDayStatisRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, channelID, termId, recordDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameDayStatisModel) Insert(ctx context.Context, data *GameDayStatis) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gameDayStatisRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.GameName, data.TermId, data.PlayerNum, data.TotalBetAmt, data.GameResult, data.PreBetNum, data.IngBetNum, data.PreBetAmt, data.IngBetAmt, data.FeeAmt, data.PreCashoutNum, data.IngCashoutNum, data.PreCashoutAmt, data.IngCashoutAmt, data.TotalBonus, data.BonusRate, data.CtrlStatus, data.RecordDate, data.Currency)
	return ret, err
}

func (m *defaultGameDayStatisModel) Update(ctx context.Context, newData *GameDayStatis) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameDayStatisRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.GameName, newData.TermId, newData.PlayerNum, newData.TotalBetAmt, newData.GameResult, newData.PreBetNum, newData.IngBetNum, newData.PreBetAmt, newData.IngBetAmt, newData.FeeAmt, newData.PreCashoutNum, newData.IngCashoutNum, newData.PreCashoutAmt, newData.IngCashoutAmt, newData.TotalBonus, newData.BonusRate, newData.CtrlStatus, newData.RecordDate, newData.Currency, newData.Id)
	return err
}

func (m *defaultGameDayStatisModel) tableName() string {
	return m.table
}
