// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	jackpotConfigFieldNames          = builder.RawFieldNames(&JackpotConfig{})
	jackpotConfigRows                = strings.Join(jackpotConfigFieldNames, ",")
	jackpotConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(jackpotConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	jackpotConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(jackpotConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	jackpotConfigModel interface {
		Insert(ctx context.Context, data *JackpotConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*JackpotConfig, error)
		FindOneByChannelIdGameName(ctx context.Context, channelId int64, gameName string) (*JackpotConfig, error)
		Update(ctx context.Context, data *JackpotConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultJackpotConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	JackpotConfig struct {
		Id                int64     `db:"id"`                  // 主键
		ChannelId         int64     `db:"channel_id"`          // 渠道ID
		ClientId          string    `db:"client_id"`           // 代理商ID
		GameName          string    `db:"game_name"`           // 游戏名称
		IsJackpotEnabled  int64     `db:"is_jackpot_enabled"`  // 是否开启奖池 0=否 1=是
		OrderAmountRatio  float64   `db:"order_amount_ratio"`  // 奖池抽取订单金额比例（%）
		TriggerOrderCount int64     `db:"trigger_order_count"` // 触发奖池需要的赛前投注单数
		PrizeRatio1St     float64   `db:"prize_ratio_1st"`     // 第1名奖金比例（%）
		PrizeRatio2Nd     float64   `db:"prize_ratio_2nd"`     // 第2名奖金比例（%）
		PrizeRatio3Rd     float64   `db:"prize_ratio_3rd"`     // 第3名奖金比例（%）
		MaxPrizeMultiple  int64     `db:"max_prize_multiple"`  // 奖金的最大投注倍数
		EatAllDivisor     int64     `db:"eat_all_divisor"`     // 通吃约数（用于计算最大抽取比例）
		CreateTime        time.Time `db:"create_time"`
		UpdateTime        time.Time `db:"update_time"`
	}
)

func newJackpotConfigModel(conn sqlx.SqlConn) *defaultJackpotConfigModel {
	return &defaultJackpotConfigModel{
		conn:  conn,
		table: "`jackpot_config`",
	}
}

func (m *defaultJackpotConfigModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJackpotConfigModel) FindOne(ctx context.Context, id int64) (*JackpotConfig, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jackpotConfigRows, m.table)
	var resp JackpotConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJackpotConfigModel) FindOneByChannelIdGameName(ctx context.Context, channelId int64, gameName string) (*JackpotConfig, error) {
	var resp JackpotConfig
	query := fmt.Sprintf("select %s from %s where `channel_id` = ? and `game_name` = ? limit 1", jackpotConfigRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, channelId, gameName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJackpotConfigModel) Insert(ctx context.Context, data *JackpotConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, jackpotConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.ClientId, data.GameName, data.IsJackpotEnabled, data.OrderAmountRatio, data.TriggerOrderCount, data.PrizeRatio1St, data.PrizeRatio2Nd, data.PrizeRatio3Rd, data.MaxPrizeMultiple, data.EatAllDivisor)
	return ret, err
}

func (m *defaultJackpotConfigModel) Update(ctx context.Context, newData *JackpotConfig) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, jackpotConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChannelId, newData.ClientId, newData.GameName, newData.IsJackpotEnabled, newData.OrderAmountRatio, newData.TriggerOrderCount, newData.PrizeRatio1St, newData.PrizeRatio2Nd, newData.PrizeRatio3Rd, newData.MaxPrizeMultiple, newData.EatAllDivisor, newData.Id)
	return err
}

func (m *defaultJackpotConfigModel) tableName() string {
	return m.table
}
