// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	jackpotRecordFieldNames          = builder.RawFieldNames(&JackpotRecord{})
	jackpotRecordRows                = strings.Join(jackpotRecordFieldNames, ",")
	jackpotRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(jackpotRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	jackpotRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(jackpotRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	jackpotRecordModel interface {
		Insert(ctx context.Context, data *JackpotRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*JackpotRecord, error)
		Update(ctx context.Context, data *JackpotRecord) error
		Delete(ctx context.Context, id int64) error
		getPage(ctx context.Context, args *JackpotRecordListArgs) ([]*JackpotRecord, int, error)
	}

	defaultJackpotRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	JackpotRecord struct {
		Id              int64     `db:"id"`                // 主键ID
		ChannelId       int64     `db:"channel_id"`        // 游戏渠道ID
		ClientId        string    `db:"client_id"`         // 代理商ID
		GameName        string    `db:"game_name"`         // 游戏名称
		TermId          int       `db:"term_id"`           // 游戏期数ID
		Ctime           int64     `db:"ctime"`             // 创建时间戳
		EndTime         time.Time `db:"end_time"`          // 期数结束时间
		Currency        string    `db:"currency"`          // 投注币种
		ValidBetAmount  int64     `db:"valid_bet_amount"`  // 有效投注金额*10,000
		JackpotInAmount int64     `db:"jackpot_in_amount"` // 计入奖池金额*10,000
		JackpotPrize1   int64     `db:"jackpot_prize_1"`   // 派奖金额1*10,000
		JackpotPrize2   int64     `db:"jackpot_prize_2"`   // 派奖金额2*10,000
		JackpotPrize3   int64     `db:"jackpot_prize_3"`   // 派奖金额3*10,000
		JackpotBalance  int64     `db:"jackpot_balance"`   // 奖池余额*10,000
		CreateTime      time.Time `db:"create_time"`
		UpdateTime      time.Time `db:"update_time"`
	}
)

func newJackpotRecordModel(conn sqlx.SqlConn) *defaultJackpotRecordModel {
	return &defaultJackpotRecordModel{
		conn:  conn,
		table: "`jackpot_record`",
	}
}

func (m *defaultJackpotRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJackpotRecordModel) FindOne(ctx context.Context, id int64) (*JackpotRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jackpotRecordRows, m.table)
	var resp JackpotRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJackpotRecordModel) Insert(ctx context.Context, data *JackpotRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, jackpotRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query,
		data.ChannelId, data.ClientId, data.GameName, data.TermId,
		data.Ctime, data.EndTime, data.Currency, data.ValidBetAmount, data.JackpotInAmount,
		data.JackpotPrize1, data.JackpotPrize2, data.JackpotPrize3, data.JackpotBalance)
	return ret, err
}

func (m *defaultJackpotRecordModel) Update(ctx context.Context, data *JackpotRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, jackpotRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query,
		data.ChannelId, data.ClientId, data.GameName, data.TermId,
		data.Ctime, data.EndTime, data.Currency, data.ValidBetAmount, data.JackpotInAmount,
		data.JackpotPrize1, data.JackpotPrize2, data.JackpotPrize3, data.JackpotBalance,
		data.Id)
	return err
}

func (m *defaultJackpotRecordModel) tableName() string {
	return m.table
}

func (m *defaultJackpotRecordModel) getPage(ctx context.Context, args *JackpotRecordListArgs) ([]*JackpotRecord, int, error) {
	var (
		where  []string
		params []interface{}
	)
	if args.ChannelId > 0 {
		where = append(where, "channel_id = ?")
		params = append(params, args.ChannelId)
	}
	if args.ClientId != "" {
		where = append(where, "client_id = ?")
		params = append(params, args.ClientId)
	}
	if args.GameName != "" {
		where = append(where, "game_name = ?")
		params = append(params, args.GameName)
	}
	if args.Currency != "" {
		where = append(where, "currency = ?")
		params = append(params, args.Currency)
	}
	if args.TermId > 0 {
		where = append(where, "term_id = ?")
		params = append(params, args.TermId)
	}
	if args.StartTime != "" {
		where = append(where, "end_time >= ?")
		params = append(params, args.StartTime)
	}
	if args.EndTime != "" {
		where = append(where, "end_time <= ?")
		params = append(params, args.EndTime)
	}
	whereSql := ""
	if len(where) > 0 {
		whereSql = "WHERE " + strings.Join(where, " AND ")
	}
	// 查询总数
	countSql := fmt.Sprintf("SELECT COUNT(*) FROM %s %s", m.table, whereSql)
	var total int
	err := m.conn.QueryRowCtx(ctx, &total, countSql, params...)
	if err != nil {
		return nil, 0, err
	}
	// 查询数据
	listSql := fmt.Sprintf("SELECT %s FROM %s %s ORDER BY end_time DESC LIMIT ? OFFSET ?", jackpotRecordRows, m.table, whereSql)
	paramsList := append(params, args.PageSize, args.Start)
	var list []*JackpotRecord
	err = m.conn.QueryRowsCtx(ctx, &list, listSql, paramsList...)
	if err != nil && err != sqlx.ErrNotFound {
		return nil, 0, err
	}
	return list, total, nil
}
