// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	taskPositionFieldNames          = builder.RawFieldNames(&TaskPosition{})
	taskPositionRows                = strings.Join(taskPositionFieldNames, ",")
	taskPositionRowsExpectAutoSet   = strings.Join(stringx.Remove(taskPositionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	taskPositionRowsWithPlaceHolder = strings.Join(stringx.Remove(taskPositionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	taskPositionModel interface {
		Insert(ctx context.Context, data *TaskPosition) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TaskPosition, error)
		FindOneByTaskName(ctx context.Context, taskName string) (*TaskPosition, error)
		Update(ctx context.Context, data *TaskPosition) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTaskPositionModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TaskPosition struct {
		Id         int64  `db:"id"`
		TaskName   string `db:"task_name"`   // 任务名称
		PositionId int64  `db:"position_id"` // 当前任务跑到的偏移量id
	}
)

func newTaskPositionModel(conn sqlx.SqlConn) *defaultTaskPositionModel {
	return &defaultTaskPositionModel{
		conn:  conn,
		table: "`task_position`",
	}
}

func (m *defaultTaskPositionModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTaskPositionModel) FindOne(ctx context.Context, id int64) (*TaskPosition, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", taskPositionRows, m.table)
	var resp TaskPosition
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskPositionModel) FindOneByTaskName(ctx context.Context, taskName string) (*TaskPosition, error) {
	var resp TaskPosition
	query := fmt.Sprintf("select %s from %s where `task_name` = ? limit 1", taskPositionRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, taskName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskPositionModel) Insert(ctx context.Context, data *TaskPosition) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, taskPositionRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TaskName, data.PositionId)
	return ret, err
}

func (m *defaultTaskPositionModel) Update(ctx context.Context, newData *TaskPosition) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, taskPositionRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TaskName, newData.PositionId, newData.Id)
	return err
}

func (m *defaultTaskPositionModel) tableName() string {
	return m.table
}
