// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	userProfitFieldNames          = builder.RawFieldNames(&UserProfit{})
	userProfitRows                = strings.Join(userProfitFieldNames, ",")
	userProfitRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfitRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfitFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userProfitModel interface {
		Insert(ctx context.Context, data *UserProfit) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserProfit, error)
		FindOneByUserIdChannelId(ctx context.Context, userId int64, channelId int64) (*UserProfit, error)
		Update(ctx context.Context, data *UserProfit) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserProfitModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserProfit struct {
		Id              int64           `db:"id"`
		UserId          int64           `db:"user_id"`           // 用户id
		ChannelId       int64           `db:"channel_id"`        // 游戏渠道id
		GameName        string          `db:"game_name"`         // 游戏名称
		BetAmt3Days     decimal.Decimal `db:"bet_amt_3days"`     // 近3日投注总额
		PumpAmt3Days    decimal.Decimal `db:"pump_amt_3days"`    // 近3日抽水总额
		CashoutAmt3Days decimal.Decimal `db:"cashout_amt_3days"` // 近3日兑现总额
		ProfitAmt3Days  decimal.Decimal `db:"profit_amt_3days"`  // 近3日盈亏总额  盈亏总额=兑现总额-投注总额+抽水总额
		Rate3Days       int64           `db:"rate_3days"`        // 近3日杀率 = 兑现总额/投注总额，字段值=实际值*1000000
		BetAmt7Days     decimal.Decimal `db:"bet_amt_7days"`     // 近7日投注总额
		PumpAmt7Days    decimal.Decimal `db:"pump_amt_7days"`    // 近7日抽水总额
		CashoutAmt7Days decimal.Decimal `db:"cashout_amt_7days"` // 近7日兑现总额
		ProfitAmt7Days  decimal.Decimal `db:"profit_amt_7days"`  // 近7日盈亏总额
		Rate7Days       int64           `db:"rate_7days"`        // 近7日杀率 = 兑现总额/投注总额，字段值=实际值*1000000
		TotalBetAmt     decimal.Decimal `db:"total_bet_amt"`     // 投注总额
		TotalPupmAmt    decimal.Decimal `db:"total_pupm_amt"`    // 抽水总额
		TotalCashoutAmt decimal.Decimal `db:"total_cashout_amt"` // 兑现总额
		TotalProfitAmt  decimal.Decimal `db:"total_profit_amt"`  // 盈亏总额
		TotalRate       int64           `db:"total_rate"`        // 总杀率 = 兑现总额/投注总额，字段值=实际值*1000000
		Status          int64           `db:"status"`            // 状态 1=正常 2=禁用
		CreateTime      time.Time       `db:"create_time"`       // 创建时间
	}
)

func newUserProfitModel(conn sqlx.SqlConn) *defaultUserProfitModel {
	return &defaultUserProfitModel{
		conn:  conn,
		table: "`user_profit`",
	}
}

func (m *defaultUserProfitModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserProfitModel) FindOne(ctx context.Context, id int64) (*UserProfit, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfitRows, m.table)
	var resp UserProfit
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfitModel) FindOneByUserIdChannelId(ctx context.Context, userId int64, channelId int64) (*UserProfit, error) {
	var resp UserProfit
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `channel_id` = ? limit 1", userProfitRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, channelId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfitModel) Insert(ctx context.Context, data *UserProfit) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userProfitRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ChannelId, data.GameName, data.BetAmt3Days, data.PumpAmt3Days, data.CashoutAmt3Days, data.ProfitAmt3Days, data.Rate3Days, data.BetAmt7Days, data.PumpAmt7Days, data.CashoutAmt7Days, data.ProfitAmt7Days, data.Rate7Days, data.TotalBetAmt, data.TotalPupmAmt, data.TotalCashoutAmt, data.TotalProfitAmt, data.TotalRate, data.Status)
	return ret, err
}

func (m *defaultUserProfitModel) Update(ctx context.Context, newData *UserProfit) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userProfitRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.ChannelId, newData.GameName, newData.BetAmt3Days, newData.PumpAmt3Days, newData.CashoutAmt3Days, newData.ProfitAmt3Days, newData.Rate3Days, newData.BetAmt7Days, newData.PumpAmt7Days, newData.CashoutAmt7Days, newData.ProfitAmt7Days, newData.Rate7Days, newData.TotalBetAmt, newData.TotalPupmAmt, newData.TotalCashoutAmt, newData.TotalProfitAmt, newData.TotalRate, newData.Status, newData.Id)
	return err
}

func (m *defaultUserProfitModel) tableName() string {
	return m.table
}
