// Code generated by goctl. DO NOT EDIT.

package gmmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"

	"github.com/shopspring/decimal"
)

var (
	userProfitDayFieldNames          = builder.RawFieldNames(&UserProfitDay{})
	userProfitDayRows                = strings.Join(userProfitDayFieldNames, ",")
	userProfitDayRowsExpectAutoSet   = strings.Join(stringx.Remove(userProfitDayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userProfitDayRowsWithPlaceHolder = strings.Join(stringx.Remove(userProfitDayFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userProfitDayModel interface {
		Insert(ctx context.Context, data *UserProfitDay) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserProfitDay, error)
		FindOneByUserIdChannelIdRecordDate(ctx context.Context, userId int64, channelId int64, recordDate int64) (*UserProfitDay, error)
		Update(ctx context.Context, data *UserProfitDay) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserProfitDayModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserProfitDay struct {
		Id         int64           `db:"id"`
		UserId     int64           `db:"user_id"`     // 用户id
		ChannelId  int64           `db:"channel_id"`  // 游戏渠道id
		BetAmt     decimal.Decimal `db:"bet_amt"`     // 投注总额
		PupmAmt    decimal.Decimal `db:"pupm_amt"`    // 抽水总额
		CashoutAmt decimal.Decimal `db:"cashout_amt"` // 兑现总额
		ProfitAmt  decimal.Decimal `db:"profit_amt"`  // 盈亏总额
		Rate       int64           `db:"rate"`        // 总杀率 = 兑现总额/投注总额，字段值=实际值*1000000
		RecordDate int64           `db:"record_date"` // 日期， 格式：YYYYMMDD, 如：20240604
		CreateTime time.Time       `db:"create_time"` // 创建时间
	}
)

func newUserProfitDayModel(conn sqlx.SqlConn) *defaultUserProfitDayModel {
	return &defaultUserProfitDayModel{
		conn:  conn,
		table: "`user_profit_day`",
	}
}

func (m *defaultUserProfitDayModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserProfitDayModel) FindOne(ctx context.Context, id int64) (*UserProfitDay, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userProfitDayRows, m.table)
	var resp UserProfitDay
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfitDayModel) FindOneByUserIdChannelIdRecordDate(ctx context.Context, userId int64, channelId int64, recordDate int64) (*UserProfitDay, error) {
	var resp UserProfitDay
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `channel_id` = ? and `record_date` = ? limit 1", userProfitDayRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, channelId, recordDate)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserProfitDayModel) Insert(ctx context.Context, data *UserProfitDay) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userProfitDayRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ChannelId, data.BetAmt, data.PupmAmt, data.CashoutAmt, data.ProfitAmt, data.Rate, data.RecordDate)
	return ret, err
}

func (m *defaultUserProfitDayModel) Update(ctx context.Context, newData *UserProfitDay) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userProfitDayRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.ChannelId, newData.BetAmt, newData.PupmAmt, newData.CashoutAmt, newData.ProfitAmt, newData.Rate, newData.RecordDate, newData.Id)
	return err
}

func (m *defaultUserProfitDayModel) tableName() string {
	return m.table
}
