CREATE TABLE `channel_day_statis` (
                                      `id` int NOT NULL AUTO_INCREMENT,
                                      `client_id` int NOT NULL DEFAULT '0' COMMENT '渠道id',
                                      `game_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '游戏名称',
                                      `player_num` int NOT NULL DEFAULT '0' COMMENT '总游戏人次',
                                      `play_num` int NOT NULL DEFAULT '0' COMMENT '总局数=当前进行的所有有效局数',
                                      `pre_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前下注金额=当天所有局数的游戏前下注之和',
                                      `pre_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前兑现金额=当天所有局数的游戏前下注的中奖金额之和',
                                      `ing_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中下注金额=当天所有局数的游戏中下注之和',
                                      `ing_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中兑现金额=当天所有局数的游戏中下注的中奖金额之和',
                                      `fee_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总服务费',
                                      `total_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '玩家总下注=当天所有局数的总下注之和',
                                      `total_bonus` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总返奖金额=当天所有局数的总中奖金额之和',
                                      `bonus_rate` int NOT NULL DEFAULT '0' COMMENT '返奖率=总中奖金额/玩家总下注  存储值=返奖率*10000',
                                      `one_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果为1的局数',
                                      `two_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在(1,2)的局数',
                                      `five_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[2,5)的局数',
                                      `ten_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[5~10)的局数',
                                      `ten_more_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[10,MAX]的局数',
                                      `record_date` int NOT NULL DEFAULT '0' COMMENT '数据归属日期 格式：YYYYMMDD ，如：20240531',
                                      `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
                                      PRIMARY KEY (`id`) USING BTREE,
                                      UNIQUE KEY `record_date` (`record_date`, `client_id`) USING BTREE,
                                      KEY `client_id` (`client_id`, `record_date`, `bonus_rate`) USING BTREE,
                                      KEY `tz` (`record_date`, `bonus_rate`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 297 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '各渠道数据日统计总表'