CREATE TABLE `game_day_statis` (
                                   `id` int NOT NULL AUTO_INCREMENT,
                                   `client_id` int NOT NULL DEFAULT '0' COMMENT '渠道id',
                                   `game_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '游戏名称',
                                   `term_id` bigint NOT NULL DEFAULT '0' COMMENT '每一局游戏的id',
                                   `player_num` int NOT NULL DEFAULT '0' COMMENT '单局参与游戏的总玩家数',
                                   `total_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '单局的总下注金额',
                                   `game_result` decimal(10, 2) NOT NULL DEFAULT '0.00' COMMENT '单局的倍数结果',
                                   `pre_bet_num` int NOT NULL DEFAULT '0' COMMENT '游戏前下注人次，游戏前下注的总玩家人次数',
                                   `ing_bet_num` int NOT NULL DEFAULT '0' COMMENT '游戏中下注人次，游戏中下注的总玩家人次数',
                                   `pre_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前下注的总投注金额',
                                   `ing_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中下注的总投注金额',
                                   `fee_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中下注的总服务费金额',
                                   `pre_cashout_num` int NOT NULL DEFAULT '0' COMMENT '游戏前下注的订单中兑现的人次数',
                                   `ing_cashout_num` int NOT NULL DEFAULT '0' COMMENT '游戏中下注的订单中兑现的人次数',
                                   `pre_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前下注的订单中兑现的总金额',
                                   `ing_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中下注的订单中兑现的总金额',
                                   `total_bonus` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '兑现成功玩家的返奖总额',
                                   `bonus_rate` int NOT NULL DEFAULT '0' COMMENT '单局返奖率=总中奖金额/玩家总下注 *10000',
                                   `ctrl_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '控局状态 1=正常 2=控输 3=控赢',
                                   `record_date` bigint NOT NULL DEFAULT '0' COMMENT '数据归属日期 格式YYYYMMDDHHmmss 如20240531235959',
                                   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
                                   PRIMARY KEY (`id`) USING BTREE,
                                   UNIQUE KEY `round_id` (`term_id`, `record_date`) USING BTREE,
                                   KEY `record_date` (`record_date`, `ctrl_status`) USING BTREE,
                                   KEY `client_id` (`client_id`, `ctrl_status`, `record_date`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 196112 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '各游戏数据每日每局统计表'