CREATE TABLE `user_profit` (
                               `id` int NOT NULL AUTO_INCREMENT,
                               `user_id` int NOT NULL DEFAULT '0' COMMENT '用户id',
                               `channel_id` int NOT NULL DEFAULT '0' COMMENT '游戏渠道id',
                               `game_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '游戏名称',
                               `bet_amt_3days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近3日投注总额',
                               `pump_amt_3days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近3日抽水总额',
                               `cashout_amt_3days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近3日兑现总额',
                               `profit_amt_3days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近3日盈亏总额  盈亏总额=兑现总额-投注总额+抽水总额',
                               `rate_3days` int NOT NULL DEFAULT '0' COMMENT '近3日杀率 = 兑现总额/投注总额，字段值=实际值*1000000',
                               `bet_amt_7days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近7日投注总额',
                               `pump_amt_7days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近7日抽水总额',
                               `cashout_amt_7days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近7日兑现总额',
                               `profit_amt_7days` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '近7日盈亏总额',
                               `rate_7days` int NOT NULL DEFAULT '0' COMMENT '近7日杀率 = 兑现总额/投注总额，字段值=实际值*1000000',
                               `total_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '投注总额',
                               `total_pupm_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '抽水总额',
                               `total_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '兑现总额',
                               `total_profit_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '盈亏总额',
                               `total_rate` int NOT NULL DEFAULT '0' COMMENT '总杀率 = 兑现总额/投注总额，字段值=实际值*1000000',
                               `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1=正常 2=禁用',
                               `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               PRIMARY KEY (`id`) USING BTREE,
                               UNIQUE KEY `user_id` (`user_id`, `channel_id`) USING BTREE,
                               KEY `channel_id` (`channel_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4321 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '用户盈亏统计表'