CREATE TABLE `channel` (
                           `id` int NOT NULL AUTO_INCREMENT COMMENT '渠道ID',
                           `client_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'apisys 渠道ID',
                           `client_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '渠道名称',
                           `game_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '游戏名称',
                           `is_active` tinyint NOT NULL DEFAULT '2' COMMENT '是否运行 1=正常 2=禁止',
                           `tz` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '渠道时区(tzdata)',
                           `ctrl_hours` tinyint(1) NOT NULL DEFAULT '0' COMMENT '运营日修正时间',
                           `service_fee` int NOT NULL DEFAULT '400' COMMENT '服务费率（*10,000）',
                           `rake` int NOT NULL DEFAULT '300' COMMENT '抽水率（*10,000）',
                           `ctrl_trigger_rate` int NOT NULL DEFAULT '0' COMMENT '调控触发率（*10,000）',
                           `ctrl_put_rate` int NOT NULL DEFAULT '1000' COMMENT '调控池输出率（*10,000）',
                           `total_profit` bigint NOT NULL DEFAULT '0' COMMENT '总盈利池（*10,000）',
                           `ctrl_profit` bigint NOT NULL DEFAULT '0' COMMENT '调控池（*10,000）',
                           `ctrl_coef` smallint NOT NULL DEFAULT '100' COMMENT '调控系数k',
                           `divisor` smallint NOT NULL DEFAULT '37' COMMENT '通吃约数c',
                           `inc_num` float(6, 5) NOT NULL DEFAULT '1.00694' COMMENT '增长指数',
  `min_bet_num` int NOT NULL DEFAULT '10' COMMENT '最小投注金额',
  `max_bet_num` int NOT NULL DEFAULT '50000' COMMENT '最大投注金额',
  `max_cashout_multiple` int NOT NULL DEFAULT '1000' COMMENT '最大兑现倍数',
  `max_cashout_per_bet` int NOT NULL DEFAULT '500000' COMMENT '单注最大盈利',
  `next_rand_multiple` int NOT NULL DEFAULT '0' COMMENT '下局随机爆点结果 (*100)',
  `next_rand_multiple_used` tinyint(1) NOT NULL DEFAULT '1' COMMENT '下局水机爆点设置是否被使用 1=否 2=是',
  `break_payout_rate` int NOT NULL DEFAULT '9700' COMMENT '爆点赔付比例(*10,000)',
  `user_profit_correct` int NOT NULL DEFAULT '0' COMMENT '用户盈亏修正比例 (*10,000)',
  `next_is_ctrl` tinyint(1) NOT NULL DEFAULT '1' COMMENT '下局是否控制 1=否 2=是',
  `total_bet_amt` bigint NOT NULL DEFAULT '0' COMMENT '总注单金额(*10,000)',
  `total_cashed_amt` bigint NOT NULL DEFAULT '0' COMMENT '总兑现金额(*10,000)',
  `bet_amt_decimal` tinyint(1) NOT NULL DEFAULT '2' COMMENT '注单金额小数位',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `stat_time_offset` smallint NOT NULL DEFAULT '0' COMMENT '统计时间偏移小时数,范围0~24',
  `agent_time_zone` smallint NOT NULL DEFAULT '0' COMMENT '代理商时区偏移小时数,范围-12~12',
  `channel_type` smallint unsigned NOT NULL DEFAULT '0' COMMENT '渠道类型：0：默认老玩法，一个渠道拥有独立的随机值开局结束，1：链上玩法，所有链上渠道共用同一个游戏期数、开始结束。19998：链上依赖的爆点渠道，19999：链上依赖的火箭渠道',
  `ui_layout` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'UI布局方式：0=弹窗，1=无缝',
  `default_line_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '默认所有线路状态：0=开（默认），1=关',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `uk_client_id` (`client_id`) USING BTREE,
  KEY `idx_client_game` (`client_id`, `game_name`)
) ENGINE = InnoDB AUTO_INCREMENT = 20000 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC COMMENT = '游戏渠道表'
