CREATE TABLE `crash_term` (
                              `id` int NOT NULL AUTO_INCREMENT COMMENT '游戏期数ID',
                              `term_id` bigint unsigned DEFAULT NULL COMMENT '渠道内连续期数(从1开始)',
                              `channel_id` int NOT NULL COMMENT '渠道ID',
                              `multiple` int NOT NULL DEFAULT '0' COMMENT '爆点倍数*100',
                              `is_control` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否控制 1=否 2=是',
                              `is_crashed` tinyint NOT NULL DEFAULT '1' COMMENT '是否爆炸 1=否 2=是',
                              `bouns_pool_start` bigint NOT NULL DEFAULT '0' COMMENT '初始调控池转入金额（*10,000）',
                              `bouns_pool` bigint NOT NULL DEFAULT '0' COMMENT '本局游戏的奖池 （*10,000）',
                              `term_hash` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '结果hash',
                              `sha512_seed` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'sha512种子',
                              `total_bet_amt` bigint NOT NULL DEFAULT '0' COMMENT '总投注额 (*10,000)',
                              `fee_amt` bigint NOT NULL DEFAULT '0' COMMENT '总服务费（*10,,000）',
                              `user_profit_correct` int NOT NULL DEFAULT '0' COMMENT '本局使用的用户盈亏修正比例 (*10,000)',
                              `rake_amt` bigint NOT NULL DEFAULT '0' COMMENT '累计抽水金额(*10,000)',
                              `cashed_amt` bigint NOT NULL DEFAULT '0' COMMENT '已兑现总金额(*10,000)',
                              `ctrl_cashed_amt` bigint NOT NULL DEFAULT '0' COMMENT '控制状态下已兑现的总金额(*10,000)',
                              `manual_squib` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否手动引爆 1=是  2=否',
                              `manual_squib_state` tinyint(1) NOT NULL DEFAULT '0' COMMENT '手动引爆阶段 0=未引爆 1=准备阶段 2=启动阶段 3=飞行阶段',
                              `break_payout_rate` int NOT NULL DEFAULT '9700' COMMENT '本局使用的爆点赔付比例 (*10,000)',
                              `profit_amt` bigint NOT NULL DEFAULT '0' COMMENT '本局使用的用户盈亏修正金额(*10,000)',
                              `max_cashedout_bet_id` int NOT NULL DEFAULT '0' COMMENT '已兑现的最大倍数的注单id',
                              `max_multiple` int NOT NULL DEFAULT '0' COMMENT '本局最大兑现倍数(*100)',
                              `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                              `pre_start_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏开始时间戳',
                              `starting_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏启动时间戳',
                              `flying_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏飞行开始时间戳',
                              `crashed_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏结束时间戳',
                              `ctime` bigint NOT NULL DEFAULT '0' COMMENT '创建时间戳',
                              PRIMARY KEY (`id`) USING BTREE,
                              UNIQUE KEY `uniq_channel_term_id` (`channel_id`, `term_id`),
                              KEY `channel_id` (`channel_id`, `is_crashed`) USING BTREE,
                              KEY `idx_crashed_time` (`crashed_time`),
                              KEY `idx_term_id` (`term_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 23939329 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC COMMENT = '游戏期数表'