apiVersion: v1
kind: ConfigMap
metadata:
  name: realtime-config
  namespace: realtime
data:
  TZ: "Asia/Shanghai"

  FRONTEND_PORT: "8080"
  API_PORT: "18080"

  API_BASE_URL: "http://realtime-api:18080"

  APP_ENV: "prod"