apiVersion: v1
kind: ConfigMap
metadata:
  name: realtime-config
  namespace: realtime
data:
  TZ: "Asia/Shanghai"
  FRONTEND_LISTEN_ADDR: ":8080"
  GAME_BACKEND_URL: "http://realtime-api:18080"
  APP_ENV: "prod"