CREATE TABLE `channel_day_statis` (
  `id` int NOT NULL AUTO_INCREMENT,
  `client_id` int NOT NULL DEFAULT '0' COMMENT '渠道id',
  `game_name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '游戏名称',
  `currency` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '货币代码',
  `player_num` int NOT NULL DEFAULT '0' COMMENT '总游戏人次',
  `total_player_num` int NOT NULL DEFAULT '0' COMMENT '总游戏人数，基于投注订单去重的会员人数',
  `play_num` int NOT NULL DEFAULT '0' COMMENT '总局数=当前进行的所有有效局数',
  `pre_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前下注金额=当天所有局数的游戏前下注之和',
  `pre_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏前兑现金额=当天所有局数的游戏前下注的中奖金额之和',
  `ing_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中下注金额=当天所有局数的游戏中下注之和',
  `ing_cashout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '游戏中兑现金额=当天所有局数的游戏中下注的中奖金额之和',
  `fee_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总服务费',
  `total_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '玩家总下注=当天所有局数的总下注之和',
  `total_valid_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总有效投注金额，因有取消投注，所以统计真实的投注',
  `prize_pool_add_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '奖池增加金额，统计奖池新增的金额',
  `prize_pool_payout_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '奖池派发金额，统计奖池派发出去的金额',
  `prize_pool_valid_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '奖池有效投注金额=总现有奖池-奖池派发金额',
  `prize_pool_rate` int NOT NULL DEFAULT '0' COMMENT '奖池率=总盈亏/总有效投注金额*100，总有效投注=0时，显示固定文案',
  `total_bonus` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总返奖金额=当天所有局数的总中奖金额之和',
  `bonus_rate` int NOT NULL DEFAULT '0' COMMENT '返奖率=总中奖金额/玩家总下注  存储值=返奖率*10000',
  `match_bet_player_num` int NOT NULL DEFAULT '0' COMMENT '赛事投注人数，统计参与赛事盘口的用户人次数（不去重）',
  `match_valid_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '赛事有效投注金额',
  `match_profit_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '赛事总盈亏',
  `match_kill_rate` int NOT NULL DEFAULT '0' COMMENT '赛事投注杀率',
  `rolling_bet_player_num` int NOT NULL DEFAULT '0' COMMENT '滚盘投注人数，统计参与滚盘的用户人次数（不去重）',
  `rolling_valid_bet_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '滚盘有效投注金额',
  `rolling_profit_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '滚盘总盈亏',
  `rolling_kill_rate` int NOT NULL DEFAULT '0' COMMENT '滚盘投注杀率',
  `total_profit_amt` decimal(14, 2) NOT NULL DEFAULT '0.00' COMMENT '总盈亏=总投注-总兑现',
  `total_kill_rate` int NOT NULL DEFAULT '0' COMMENT '总杀率=总盈亏/总有效投注*100',
  `one_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果为1的局数',
  `two_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在(1,2)的局数',
  `five_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[2,5)的局数',
  `ten_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[5~10)的局数',
  `ten_more_num` int NOT NULL DEFAULT '0' COMMENT '当天所有局数中倍数结果在[10,MAX]的局数',
  `record_date` int NOT NULL DEFAULT '0' COMMENT '数据归属日期 格式：YYYYMMDD ，如：20240531',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `record_date_client_currency` (`record_date`, `client_id`, `currency`) USING BTREE,
  KEY `client_id` (`client_id`, `record_date`, `bonus_rate`) USING BTREE,
  KEY `tz` (`record_date`, `bonus_rate`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 297 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '各渠道数据日统计总表'