CREATE TABLE `bet` (
                       `id` int NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
                       `api_order_no` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'apisys 订单号',
                       `channel_id` int NOT NULL DEFAULT '0' COMMENT '渠道id@channel.id',
                       `term_id` int NOT NULL COMMENT '游戏期数ID',
                       `user_id` int NOT NULL COMMENT '用户ID',
                       `user_name` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户名',
                       `user_seed` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '用户种子',
                       `bet_type` tinyint NOT NULL COMMENT '投注类型：1游戏前，2游戏中',
                       `amount` bigint NOT NULL COMMENT '投注金额*10,000 （扣除服务费后的金额）',
                       `currency` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '币种',
                       `auto_cashout_multiple` int NOT NULL COMMENT '自动兑现倍数*100',
                       `manual_cashout_multiple` int NOT NULL DEFAULT '0' COMMENT '手动兑现倍数*100',
                       `bet_at_multiple` int NOT NULL DEFAULT '0' COMMENT '投注时倍数*100',
                       `service_fee` bigint NOT NULL DEFAULT '0' COMMENT '服务费*10,000',
                       `rake` int NOT NULL DEFAULT '0' COMMENT '使用的抽水率 (*10,000)',
                       `rake_amt` int NOT NULL DEFAULT '0' COMMENT '抽水费 (*10,000)',
                       `cashed_out_amount` bigint NOT NULL COMMENT '兑现金额*10,000',
                       `order_status` int NOT NULL DEFAULT '0' COMMENT '订单状态 1000=创建中 2000=已创建 10100=创建失败 3000=兑现中 4000=已兑现 5000=退款中 6000=已退款',
                       `in_retry` tinyint NOT NULL DEFAULT '2' COMMENT '是否进入重试任务， 1=是 2=否',
                       `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                       `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                       `ctime` bigint NOT NULL DEFAULT '0' COMMENT '创建时间时间戳',
                       `game_play` int NOT NULL DEFAULT '0' COMMENT '游戏玩法',
                       `bonus_bet_id` bigint DEFAULT NULL COMMENT '奖金订单表ID',
                       `manual_cashout_times` int NOT NULL DEFAULT '0' COMMENT '手动兑现次数：记录用户主动触发兑现的次数',
                       `first_cashout_amount` bigint NOT NULL DEFAULT '0' COMMENT '第一次分步兑现金额，单位*10,000',
                       `first_manual_cashout_multiple` int NOT NULL DEFAULT '0' COMMENT '第一次分步兑现时的手动兑现倍数，单位*100',
                       `is_cashout_amount_merged` tinyint NOT NULL DEFAULT '0' COMMENT '是否已将first_cashout_amount累加进cashout_amount，1=是，0=否',
                       PRIMARY KEY (`id`) USING BTREE,
                       KEY `term_id` (`term_id`,`order_status`) USING BTREE,
                       KEY `channel_id` (`channel_id`,`order_status`,`user_id`,`ctime`) USING BTREE,
                       KEY `channel_id_2` (`channel_id`,`order_status`,`ctime`) USING BTREE,
                       KEY `api_order_no` (`api_order_no`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=998262 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='投注表'