CREATE TABLE `bonus_bet` (
                             `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
                             `bet_id` int NOT NULL COMMENT '关联的主订单ID@bet.id',
                             `channel_id` int NOT NULL DEFAULT '0' COMMENT '渠道id@channel.id',
                             `term_id` int NOT NULL COMMENT '游戏期数ID',
                             `user_id` int NOT NULL COMMENT '用户ID',
                             `bonus_order_no` varchar(60) NOT NULL DEFAULT '' COMMENT '奖金订单号',
                             `amount` bigint NOT NULL DEFAULT '0' COMMENT '下注金额*10,000（固定为0）',
                             `bet_at_multiple` int NOT NULL DEFAULT '0' COMMENT '下注时倍数*100（固定为0）',
                             `rake` int NOT NULL DEFAULT '0' COMMENT '应计抽水*10,000（固定为0）',
                             `service_fee` bigint NOT NULL DEFAULT '0' COMMENT '服务费用*10,000（固定为0）',
                             `cashout_multiple` int NOT NULL DEFAULT '0' COMMENT '兑现倍数*100',
                             `order_status` int NOT NULL DEFAULT '4000' COMMENT '订单状态（固定为已兑现）',
                             `bonus_amount` bigint NOT NULL COMMENT '获得奖金*10,000',
                             `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                             `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                             `ctime` bigint NOT NULL DEFAULT '0' COMMENT '创建时间的 Unix 时间戳（秒）',
                             `bonus_rank` int NOT NULL DEFAULT '0' COMMENT '当前奖金排名（第几名）',
                             PRIMARY KEY (`id`) USING BTREE,
                             KEY `bet_id` (`bet_id`) USING BTREE,
                             KEY `term_id` (`term_id`) USING BTREE,
                             KEY `user_id` (`user_id`) USING BTREE,
                             KEY `channel_id` (`channel_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=282 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='奖金订单表'