// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	betFieldNames          = builder.RawFieldNames(&Bet{})
	betRows                = strings.Join(betFieldNames, ",")
	betRowsExpectAutoSet   = strings.Join(stringx.Remove(betFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	betRowsWithPlaceHolder = strings.Join(stringx.Remove(betFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	betModel interface {
		Insert(ctx context.Context, data *Bet) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Bet, error)
		Update(ctx context.Context, data *Bet) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBetModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Bet struct {
		Id                         int64         `db:"id"`                            // 自增主键ID
		ApiOrderNo                 string        `db:"api_order_no"`                  // apisys 订单号
		ChannelId                  int64         `db:"channel_id"`                    // 渠道id@channel.id
		RealChannelId              int64         `db:"real_channel_id"`               // 真实渠道ID
		RuntimeChannelId           int64         `db:"runtime_channel_id"`            // 运行局渠道ID(98/99)
		TermId                     int64         `db:"term_id"`                       // 游戏期数ID
		UserId                     int64         `db:"user_id"`                       // 用户ID
		UserName                   string        `db:"user_name"`                     // 用户名
		UserSeed                   string        `db:"user_seed"`                     // 用户种子
		BetType                    int64         `db:"bet_type"`                      // 投注类型：1游戏前，2游戏中
		Amount                     int64         `db:"amount"`                        // 投注金额*10,000 （扣除服务费后的金额）
		Currency                   string        `db:"currency"`                      // 币种
		AutoCashoutMultiple        int64         `db:"auto_cashout_multiple"`         // 自动兑现倍数*100
		ManualCashoutMultiple      int64         `db:"manual_cashout_multiple"`       // 手动兑现倍数*100
		BetAtMultiple              int64         `db:"bet_at_multiple"`               // 投注时倍数*100
		ServiceFee                 int64         `db:"service_fee"`                   // 服务费*10,000
		Rake                       int64         `db:"rake"`                          // 使用的抽水率 (*10,000)
		RakeAmt                    int64         `db:"rake_amt"`                      // 抽水费 (*10,000)
		CashedOutAmount            int64         `db:"cashed_out_amount"`             // 兑现金额*10,000
		OrderStatus                int64         `db:"order_status"`                  // 订单状态 1000=创建中 2000=已创建 10100=创建失败 3000=兑现中 4000=已兑现 5000=退款中 6000=已退款
		InRetry                    int64         `db:"in_retry"`                      // 是否进入重试任务， 1=是 2=否
		CreateTime                 time.Time     `db:"create_time"`                   // 创建时间
		UpdateTime                 time.Time     `db:"update_time"`                   // 更新时间
		Ctime                      int64         `db:"ctime"`                         // 创建时间时间戳
		GamePlay                   int64         `db:"game_play"`                     // 游戏玩法
		BonusBetId                 sql.NullInt64 `db:"bonus_bet_id"`                  // 奖金订单表ID
		ManualCashoutTimes         int64         `db:"manual_cashout_times"`          // 手动兑现次数：记录用户主动触发兑现的次数
		FirstCashoutAmount         int64         `db:"first_cashout_amount"`          // 第一次分步兑现金额，单位*10,000
		FirstManualCashoutMultiple int64         `db:"first_manual_cashout_multiple"` // 第一次分步兑现时的手动兑现倍数，单位*100
		IsCashoutAmountMerged      int64         `db:"is_cashout_amount_merged"`      // 是否已将first_cashout_amount累加进cashout_amount，1=是，0=否
	}
)

func newBetModel(conn sqlx.SqlConn) *defaultBetModel {
	return &defaultBetModel{
		conn:  conn,
		table: "`bet`",
	}
}

func (m *defaultBetModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBetModel) FindOne(ctx context.Context, id int64) (*Bet, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", betRows, m.table)
	var resp Bet
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBetModel) Insert(ctx context.Context, data *Bet) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, betRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ApiOrderNo, data.ChannelId, data.RealChannelId, data.RuntimeChannelId, data.TermId, data.UserId, data.UserName, data.UserSeed, data.BetType, data.Amount, data.Currency, data.AutoCashoutMultiple, data.ManualCashoutMultiple, data.BetAtMultiple, data.ServiceFee, data.Rake, data.RakeAmt, data.CashedOutAmount, data.OrderStatus, data.InRetry, data.Ctime, data.GamePlay, data.BonusBetId, data.ManualCashoutTimes, data.FirstCashoutAmount, data.FirstManualCashoutMultiple, data.IsCashoutAmountMerged)
	return ret, err
}

func (m *defaultBetModel) Update(ctx context.Context, data *Bet) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, betRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ApiOrderNo, data.ChannelId, data.RealChannelId, data.RuntimeChannelId, data.TermId, data.UserId, data.UserName, data.UserSeed, data.BetType, data.Amount, data.Currency, data.AutoCashoutMultiple, data.ManualCashoutMultiple, data.BetAtMultiple, data.ServiceFee, data.Rake, data.RakeAmt, data.CashedOutAmount, data.OrderStatus, data.InRetry, data.Ctime, data.GamePlay, data.BonusBetId, data.ManualCashoutTimes, data.FirstCashoutAmount, data.FirstManualCashoutMultiple, data.IsCashoutAmountMerged, data.Id)
	return err
}

func (m *defaultBetModel) tableName() string {
	return m.table
}
