// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	bonusBetFieldNames          = builder.RawFieldNames(&BonusBet{})
	bonusBetRows                = strings.Join(bonusBetFieldNames, ",")
	bonusBetRowsExpectAutoSet   = strings.Join(stringx.Remove(bonusBetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	bonusBetRowsWithPlaceHolder = strings.Join(stringx.Remove(bonusBetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	bonusBetModel interface {
		Insert(ctx context.Context, data *BonusBet) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BonusBet, error)
		Update(ctx context.Context, data *BonusBet) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBonusBetModel struct {
		conn  sqlx.SqlConn
		table string
	}

	BonusBet struct {
		Id              int64     `db:"id"`               // 自增主键ID
		BetId           int64     `db:"bet_id"`           // 关联的主订单ID@bet.id
		ChannelId       int64     `db:"channel_id"`       // 渠道id@channel.id
		TermId          int64     `db:"term_id"`          // 游戏期数ID
		UserId          int64     `db:"user_id"`          // 用户ID
		BonusOrderNo    string    `db:"bonus_order_no"`   // 奖金订单号
		Amount          int64     `db:"amount"`           // 下注金额*10,000（固定为0）
		BetAtMultiple   int64     `db:"bet_at_multiple"`  // 下注时倍数*100（固定为0）
		Rake            int64     `db:"rake"`             // 应计抽水*10,000（固定为0）
		ServiceFee      int64     `db:"service_fee"`      // 服务费用*10,000（固定为0）
		CashoutMultiple int64     `db:"cashout_multiple"` // 兑现倍数*100
		OrderStatus     int64     `db:"order_status"`     // 订单状态（固定为已兑现）
		BonusAmount     int64     `db:"bonus_amount"`     // 获得奖金*10,000
		CreateTime      time.Time `db:"create_time"`      // 创建时间
		UpdateTime      time.Time `db:"update_time"`      // 更新时间
		Ctime           int64     `db:"ctime"`            // 创建时间的 Unix 时间戳（秒）
		BonusRank       int64     `db:"bonus_rank"`       // 当前排名（第几名）
	}
)

func newBonusBetModel(conn sqlx.SqlConn) *defaultBonusBetModel {
	return &defaultBonusBetModel{
		conn:  conn,
		table: "`bonus_bet`",
	}
}

func (m *defaultBonusBetModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBonusBetModel) FindOne(ctx context.Context, id int64) (*BonusBet, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", bonusBetRows, m.table)
	var resp BonusBet
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBonusBetModel) Insert(ctx context.Context, data *BonusBet) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, bonusBetRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BetId, data.ChannelId, data.TermId, data.UserId, data.BonusOrderNo, data.Amount, data.BetAtMultiple, data.Rake, data.ServiceFee, data.CashoutMultiple, data.OrderStatus, data.BonusAmount, data.Ctime, data.BonusRank)
	return ret, err
}

func (m *defaultBonusBetModel) Update(ctx context.Context, data *BonusBet) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, bonusBetRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BetId, data.ChannelId, data.TermId, data.UserId, data.BonusOrderNo, data.Amount, data.BetAtMultiple, data.Rake, data.ServiceFee, data.CashoutMultiple, data.OrderStatus, data.BonusAmount, data.Ctime, data.BonusRank, data.Id)
	return err
}

func (m *defaultBonusBetModel) tableName() string {
	return m.table
}
