// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	chainProgressFieldNames          = builder.RawFieldNames(&ChainProgress{})
	chainProgressRows                = strings.Join(chainProgressFieldNames, ",")
	chainProgressRowsExpectAutoSet   = strings.Join(stringx.Remove(chainProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	chainProgressRowsWithPlaceHolder = strings.Join(stringx.Remove(chainProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	chainProgressModel interface {
		Insert(ctx context.Context, data *ChainProgress) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChainProgress, error)
		Update(ctx context.Context, data *ChainProgress) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChainProgressModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChainProgress struct {
		Id        int64     `db:"id"`         // 自增主键
		ChannelId int64     `db:"channel_id"` // 游戏火箭or爆点
		TermId    int64     `db:"term_id"`    // 已发送到的期数ID（包含该期）
		Ctime     time.Time `db:"ctime"`      // 创建时间
		Mtime     time.Time `db:"mtime"`      // 更新时间
	}
)

func newChainProgressModel(conn sqlx.SqlConn) *defaultChainProgressModel {
	return &defaultChainProgressModel{
		conn:  conn,
		table: "`chain_progress`",
	}
}

func (m *defaultChainProgressModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChainProgressModel) FindOne(ctx context.Context, id int64) (*ChainProgress, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", chainProgressRows, m.table)
	var resp ChainProgress
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChainProgressModel) Insert(ctx context.Context, data *ChainProgress) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, chainProgressRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermId, data.Ctime, data.Mtime)
	return ret, err
}

func (m *defaultChainProgressModel) Update(ctx context.Context, data *ChainProgress) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, chainProgressRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermId, data.Ctime, data.Mtime, data.Id)
	return err
}

func (m *defaultChainProgressModel) tableName() string {
	return m.table
}
