// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelFieldNames          = builder.RawFieldNames(&Channel{})
	channelRows                = strings.Join(channelFieldNames, ",")
	channelRowsExpectAutoSet   = strings.Join(stringx.Remove(channelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelRowsWithPlaceHolder = strings.Join(stringx.Remove(channelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	channelModel interface {
		Insert(ctx context.Context, data *Channel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Channel, error)
		Update(ctx context.Context, data *Channel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChannelModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Channel struct {
		Id                   int64     `db:"id"`                      // 渠道ID
		ClientId             string    `db:"client_id"`               // apisys 渠道ID
		ClientName           string    `db:"client_name"`             // 渠道名称
		GameName             string    `db:"game_name"`               // 游戏名称
		IsActive             int64     `db:"is_active"`               // 是否运行 1=正常 2=禁止
		Tz                   string    `db:"tz"`                      // 渠道时区(tzdata)
		CtrlHours            int64     `db:"ctrl_hours"`              // 运营日修正时间
		ServiceFee           int64     `db:"service_fee"`             // 服务费率（*10,000）
		Rake                 int64     `db:"rake"`                    // 抽水率（*10,000）
		CtrlTriggerRate      int64     `db:"ctrl_trigger_rate"`       // 调控触发率（*10,000）
		CtrlPutRate          int64     `db:"ctrl_put_rate"`           // 调控池输出率（*10,000）
		TotalProfit          int64     `db:"total_profit"`            // 总盈利池（*10,000）
		CtrlProfit           int64     `db:"ctrl_profit"`             // 调控池（*10,000）
		CtrlCoef             int64     `db:"ctrl_coef"`               // 调控系数k
		Divisor              int64     `db:"divisor"`                 // 通吃约数c
		IncNum               float64   `db:"inc_num"`                 // 增长指数
		MinBetNum            int64     `db:"min_bet_num"`             // 最小投注金额
		MaxBetNum            int64     `db:"max_bet_num"`             // 最大投注金额
		MaxCashoutMultiple   int64     `db:"max_cashout_multiple"`    // 最大兑现倍数
		MaxCashoutPerBet     int64     `db:"max_cashout_per_bet"`     // 单注最大盈利
		NextRandMultiple     int64     `db:"next_rand_multiple"`      // 下局随机爆点结果 (*100)
		NextRandMultipleUsed int64     `db:"next_rand_multiple_used"` // 下局水机爆点设置是否被使用 1=否 2=是
		BreakPayoutRate      int64     `db:"break_payout_rate"`       // 爆点赔付比例(*10,000)
		UserProfitCorrect    int64     `db:"user_profit_correct"`     // 用户盈亏修正比例 (*10,000)
		NextIsCtrl           int64     `db:"next_is_ctrl"`            // 下局是否控制 1=否 2=是
		TotalBetAmt          int64     `db:"total_bet_amt"`           // 总注单金额(*10,000)
		TotalCashedAmt       int64     `db:"total_cashed_amt"`        // 总兑现金额(*10,000)
		BetAmtDecimal        int64     `db:"bet_amt_decimal"`         // 注单金额小数位
		StatTimeOffset       int64     `db:"stat_time_offset"`        // 统计时间偏移小时数
		AgentTimeZone        int64     `db:"agent_time_zone"`         // 代理商时区偏移小时数，范围-12~12
		CreateTime           time.Time `db:"create_time"`             // 创建时间
		UpdateTime           time.Time `db:"update_time"`             // 更新时间
		ChannelType          uint64    `db:"channel_type"`            // 渠道类型：0：默认老玩法，一个渠道独立随机，1：链上玩法...
		UiLayout             int64     `db:"ui_layout"`               // UI布局方式：0=弹窗，1=无缝
		DefaultLineStatus    int64     `db:"default_line_status"`     // 默认所有线路状态：0=开（默认），1=关
	}
)

func newChannelModel(conn sqlx.SqlConn) *defaultChannelModel {
	return &defaultChannelModel{
		conn:  conn,
		table: "`channel`",
	}
}

func (m *defaultChannelModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChannelModel) FindOne(ctx context.Context, id int64) (*Channel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelRows, m.table)
	var resp Channel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelModel) Insert(ctx context.Context, data *Channel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, channelRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.ClientName, data.GameName, data.IsActive, data.Tz, data.CtrlHours, data.ServiceFee, data.Rake, data.CtrlTriggerRate, data.CtrlPutRate, data.TotalProfit, data.CtrlProfit, data.CtrlCoef, data.Divisor, data.IncNum, data.MinBetNum, data.MaxBetNum, data.MaxCashoutMultiple, data.MaxCashoutPerBet, data.NextRandMultiple, data.NextRandMultipleUsed, data.BreakPayoutRate, data.UserProfitCorrect, data.NextIsCtrl, data.TotalBetAmt, data.TotalCashedAmt, data.BetAmtDecimal, data.StatTimeOffset, data.AgentTimeZone, data.ChannelType, data.UiLayout, data.DefaultLineStatus)
	return ret, err
}

func (m *defaultChannelModel) Update(ctx context.Context, data *Channel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.ClientName, data.GameName, data.IsActive, data.Tz, data.CtrlHours, data.ServiceFee, data.Rake, data.CtrlTriggerRate, data.CtrlPutRate, data.TotalProfit, data.CtrlProfit, data.CtrlCoef, data.Divisor, data.IncNum, data.MinBetNum, data.MaxBetNum, data.MaxCashoutMultiple, data.MaxCashoutPerBet, data.NextRandMultiple, data.NextRandMultipleUsed, data.BreakPayoutRate, data.UserProfitCorrect, data.NextIsCtrl, data.TotalBetAmt, data.TotalCashedAmt, data.BetAmtDecimal, data.StatTimeOffset, data.AgentTimeZone, data.ChannelType, data.UiLayout, data.DefaultLineStatus, data.Id)
	return err
}

func (m *defaultChannelModel) tableName() string {
	return m.table
}
