// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	channelTermSeedFieldNames          = builder.RawFieldNames(&ChannelTermSeed{})
	channelTermSeedRows                = strings.Join(channelTermSeedFieldNames, ",")
	channelTermSeedRowsExpectAutoSet   = strings.Join(stringx.Remove(channelTermSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	channelTermSeedRowsWithPlaceHolder = strings.Join(stringx.Remove(channelTermSeedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	channelTermSeedModel interface {
		Insert(ctx context.Context, data *ChannelTermSeed) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ChannelTermSeed, error)
		FindOneByChannelIdTermId(ctx context.Context, channelId int64, termId int64) (*ChannelTermSeed, error)
		Update(ctx context.Context, data *ChannelTermSeed) error
		Delete(ctx context.Context, id int64) error
	}

	defaultChannelTermSeedModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ChannelTermSeed struct {
		Id         int64  `db:"id"`          // 自增主键ID
		ChannelId  int64  `db:"channel_id"`  // 渠道ID
		TermId     int64  `db:"term_id"`     // 期数ID
		SeedId     string `db:"seed_id"`     // 种子ID
		SeedStatus int64  `db:"seed_status"` // 状态：0-未使用 1-已使用
		Ctime      int64  `db:"ctime"`       // 创建时间(UNIX时间戳)
	}
)

func newChannelTermSeedModel(conn sqlx.SqlConn) *defaultChannelTermSeedModel {
	return &defaultChannelTermSeedModel{
		conn:  conn,
		table: "`channel_term_seed`",
	}
}

func (m *defaultChannelTermSeedModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultChannelTermSeedModel) FindOne(ctx context.Context, id int64) (*ChannelTermSeed, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", channelTermSeedRows, m.table)
	var resp ChannelTermSeed
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelTermSeedModel) FindOneByChannelIdTermId(ctx context.Context, channelId int64, termId int64) (*ChannelTermSeed, error) {
	var resp ChannelTermSeed
	query := fmt.Sprintf("select %s from %s where `channel_id` = ? and `term_id` = ? limit 1", channelTermSeedRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, channelId, termId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultChannelTermSeedModel) Insert(ctx context.Context, data *ChannelTermSeed) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, channelTermSeedRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermId, data.SeedId, data.SeedStatus, data.Ctime)
	return ret, err
}

func (m *defaultChannelTermSeedModel) Update(ctx context.Context, newData *ChannelTermSeed) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, channelTermSeedRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChannelId, newData.TermId, newData.SeedId, newData.SeedStatus, newData.Ctime, newData.Id)
	return err
}

func (m *defaultChannelTermSeedModel) tableName() string {
	return m.table
}
