// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	crashTermFieldNames          = builder.RawFieldNames(&CrashTerm{})
	crashTermRows                = strings.Join(crashTermFieldNames, ",")
	crashTermRowsExpectAutoSet   = strings.Join(stringx.Remove(crashTermFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	crashTermRowsWithPlaceHolder = strings.Join(stringx.Remove(crashTermFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	crashTermModel interface {
		Insert(ctx context.Context, data *CrashTerm) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CrashTerm, error)
		FindOneByChannelIdTermId(ctx context.Context, channelId int64, termId int64) (*CrashTerm, error)
		Update(ctx context.Context, data *CrashTerm) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCrashTermModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CrashTerm struct {
		Id                int64     `db:"id"`
		TermId            int64     `db:"term_id"`              // 渠道内连续期数
		ChannelId         int64     `db:"channel_id"`           // 渠道ID
		Multiple          int64     `db:"multiple"`             // 爆点倍数*100
		IsControl         int64     `db:"is_control"`           // 是否控制 1=否 2=是
		IsCrashed         int64     `db:"is_crashed"`           // 是否爆炸 1=否 2=是
		BounsPoolStart    int64     `db:"bouns_pool_start"`     // 初始调控池转入金额（*10,000）
		BounsPool         int64     `db:"bouns_pool"`           // 本局游戏的奖池 （*10,000）
		TermHash          string    `db:"term_hash"`            // 结果hash
		Sha512Seed        string    `db:"sha512_seed"`          // sha512种子
		TotalBetAmt       int64     `db:"total_bet_amt"`        // 总投注额 (*10,000)
		FeeAmt            int64     `db:"fee_amt"`              // 总服务费（*10,,000）
		UserProfitCorrect int64     `db:"user_profit_correct"`  // 本局使用的用户盈亏修正比例 (*10,000)
		RakeAmt           int64     `db:"rake_amt"`             // 累计抽水金额(*10,000)
		CashedAmt         int64     `db:"cashed_amt"`           // 已兑现总金额(*10,000)
		CtrlCashedAmt     int64     `db:"ctrl_cashed_amt"`      // 控制状态下已兑现的总金额(*10,000)
		ManualSquib       int64     `db:"manual_squib"`         // 是否手动引爆 1=是  2=否
		ManualSquibState  int64     `db:"manual_squib_state"`   // 手动引爆阶段 0=未引爆 1=准备阶段 2=启动阶段 3=飞行阶段
		BreakPayoutRate   int64     `db:"break_payout_rate"`    // 本局使用的爆点赔付比例 (*10,000)
		ProfitAmt         int64     `db:"profit_amt"`           // 本局使用的用户盈亏修正金额(*10,000)
		MaxCashedoutBetId int64     `db:"max_cashedout_bet_id"` // 已兑现的最大倍数的注单id
		MaxMultiple       int64     `db:"max_multiple"`         // 本局最大兑现倍数(*100)
		CreateTime        time.Time `db:"create_time"`          // 创建时间
		UpdateTime        time.Time `db:"update_time"`          // 更新时间
		PreStartTime      int64     `db:"pre_start_time"`       // 游戏开始时间戳
		StartingTime      int64     `db:"starting_time"`        // 游戏启动时间戳
		FlyingTime        int64     `db:"flying_time"`          // 游戏飞行开始时间戳
		CrashedTime       int64     `db:"crashed_time"`         // 游戏结束时间戳
		Ctime             int64     `db:"ctime"`                // 创建时间戳
	}
)

func newCrashTermModel(conn sqlx.SqlConn) *defaultCrashTermModel {
	return &defaultCrashTermModel{
		conn:  conn,
		table: "`crash_term`",
	}
}

func (m *defaultCrashTermModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCrashTermModel) FindOne(ctx context.Context, id int64) (*CrashTerm, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", crashTermRows, m.table)
	var resp CrashTerm
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCrashTermModel) FindOneByChannelIdTermId(ctx context.Context, channelId int64, termId int64) (*CrashTerm, error) {
	var resp CrashTerm
	query := fmt.Sprintf("select %s from %s where `channel_id` = ? and `term_id` = ? limit 1", crashTermRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, channelId, termId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCrashTermModel) Insert(ctx context.Context, data *CrashTerm) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, crashTermRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.TermId, data.ChannelId, data.Multiple, data.IsControl, data.IsCrashed, data.BounsPoolStart, data.BounsPool, data.TermHash, data.Sha512Seed, data.TotalBetAmt, data.FeeAmt, data.UserProfitCorrect, data.RakeAmt, data.CashedAmt, data.CtrlCashedAmt, data.ManualSquib, data.ManualSquibState, data.BreakPayoutRate, data.ProfitAmt, data.MaxCashedoutBetId, data.MaxMultiple, data.PreStartTime, data.StartingTime, data.FlyingTime, data.CrashedTime, data.Ctime)
	return ret, err
}

func (m *defaultCrashTermModel) Update(ctx context.Context, newData *CrashTerm) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, crashTermRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TermId, newData.ChannelId, newData.Multiple, newData.IsControl, newData.IsCrashed, newData.BounsPoolStart, newData.BounsPool, newData.TermHash, newData.Sha512Seed, newData.TotalBetAmt, newData.FeeAmt, newData.UserProfitCorrect, newData.RakeAmt, newData.CashedAmt, newData.CtrlCashedAmt, newData.ManualSquib, newData.ManualSquibState, newData.BreakPayoutRate, newData.ProfitAmt, newData.MaxCashedoutBetId, newData.MaxMultiple, newData.PreStartTime, newData.StartingTime, newData.FlyingTime, newData.CrashedTime, newData.Ctime, newData.Id)
	return err
}

func (m *defaultCrashTermModel) tableName() string {
	return m.table
}
