// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameCtrlLogFieldNames          = builder.RawFieldNames(&GameCtrlLog{})
	gameCtrlLogRows                = strings.Join(gameCtrlLogFieldNames, ",")
	gameCtrlLogRowsExpectAutoSet   = strings.Join(stringx.Remove(gameCtrlLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameCtrlLogRowsWithPlaceHolder = strings.Join(stringx.Remove(gameCtrlLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameCtrlLogModel interface {
		Insert(ctx context.Context, data *GameCtrlLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameCtrlLog, error)
		Update(ctx context.Context, data *GameCtrlLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameCtrlLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameCtrlLog struct {
		Id                int64     `db:"id"`
		ClientId          int64     `db:"client_id"`           // 渠道id
		TermId            int64     `db:"term_id"`             // 游戏局数id
		UserId            int64     `db:"user_id"`             // 此操作的管理员用户id
		IsControl         int64     `db:"is_control"`          // 是否控制 1=否 2=是
		BreakPayoutRate   int64     `db:"break_payout_rate"`   // 爆点赔付比例 （*10000）
		UserProfitCorrect int64     `db:"user_profit_correct"` // 用户盈亏修正比例（*10000）
		NextRandMultiple  int64     `db:"next_rand_multiple"`  // 下局随机爆点结果 (*100)
		CreateTime        time.Time `db:"create_time"`         // 创建 时间
	}
)

func newGameCtrlLogModel(conn sqlx.SqlConn) *defaultGameCtrlLogModel {
	return &defaultGameCtrlLogModel{
		conn:  conn,
		table: "`game_ctrl_log`",
	}
}

func (m *defaultGameCtrlLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameCtrlLogModel) FindOne(ctx context.Context, id int64) (*GameCtrlLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameCtrlLogRows, m.table)
	var resp GameCtrlLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameCtrlLogModel) Insert(ctx context.Context, data *GameCtrlLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, gameCtrlLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TermId, data.UserId, data.IsControl, data.BreakPayoutRate, data.UserProfitCorrect, data.NextRandMultiple)
	return ret, err
}

func (m *defaultGameCtrlLogModel) Update(ctx context.Context, data *GameCtrlLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameCtrlLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TermId, data.UserId, data.IsControl, data.BreakPayoutRate, data.UserProfitCorrect, data.NextRandMultiple, data.Id)
	return err
}

func (m *defaultGameCtrlLogModel) tableName() string {
	return m.table
}
