// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameBlewLogFieldNames          = builder.RawFieldNames(&GameBlewLog{})
	gameBlewLogRows                = strings.Join(gameBlewLogFieldNames, ",")
	gameBlewLogRowsExpectAutoSet   = strings.Join(stringx.Remove(gameBlewLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameBlewLogRowsWithPlaceHolder = strings.Join(stringx.Remove(gameBlewLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameBlewLogModel interface {
		Insert(ctx context.Context, data *GameBlewLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameBlewLog, error)
		Update(ctx context.Context, data *GameBlewLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameBlewLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameBlewLog struct {
		Id               int64     `db:"id"`
		ClientId         int64     `db:"client_id"`          // 渠道id
		TermId           int64     `db:"term_id"`            // 游戏局数id
		UserId           int64     `db:"user_id"`            // 引爆操作的管理员用户id
		ManualSquibState int64     `db:"manual_squib_state"` // 手动引爆阶段 0=未引爆 1=准备阶段 2=启动阶段 3=飞行阶段
		CtrlResult       int64     `db:"ctrl_result"`        // 引爆结果 1=成功 2=失败
		FailMsg          string    `db:"fail_msg"`           // 引爆失败原因
		CreateTime       time.Time `db:"create_time"`        // 创建时间
	}
)

func newGameBlewLogModel(conn sqlx.SqlConn) *defaultGameBlewLogModel {
	return &defaultGameBlewLogModel{
		conn:  conn,
		table: "`game_blew_log`",
	}
}

func (m *defaultGameBlewLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameBlewLogModel) FindOne(ctx context.Context, id int64) (*GameBlewLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameBlewLogRows, m.table)
	var resp GameBlewLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameBlewLogModel) Insert(ctx context.Context, data *GameBlewLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, gameBlewLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TermId, data.UserId, data.ManualSquibState, data.CtrlResult, data.FailMsg)
	return ret, err
}

func (m *defaultGameBlewLogModel) Update(ctx context.Context, data *GameBlewLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameBlewLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.TermId, data.UserId, data.ManualSquibState, data.CtrlResult, data.FailMsg, data.Id)
	return err
}

func (m *defaultGameBlewLogModel) tableName() string {
	return m.table
}
