// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameTermIdFieldNames          = builder.RawFieldNames(&GameTermId{})
	gameTermIdRows                = strings.Join(gameTermIdFieldNames, ",")
	gameTermIdRowsExpectAutoSet   = strings.Join(stringx.Remove(gameTermIdFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameTermIdRowsWithPlaceHolder = strings.Join(stringx.Remove(gameTermIdFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameTermIdModel interface {
		Insert(ctx context.Context, data *GameTermId) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameTermId, error)
		FindOneByTermId(ctx context.Context, termId int64) (*GameTermId, error)
		Update(ctx context.Context, data *GameTermId) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameTermIdModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameTermId struct {
		Id         int64 `db:"id"`
		ChannelId  int64 `db:"channel_id"`   // 游戏id
		TermId     int64 `db:"term_id"`      // 局id @crash_term.id
		GameTermId int64 `db:"game_term_id"` // 游戏下的局id
	}
)

func newGameTermIdModel(conn sqlx.SqlConn) *defaultGameTermIdModel {
	return &defaultGameTermIdModel{
		conn:  conn,
		table: "`game_term_id`",
	}
}

func (m *defaultGameTermIdModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameTermIdModel) FindOne(ctx context.Context, id int64) (*GameTermId, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameTermIdRows, m.table)
	var resp GameTermId
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTermIdModel) FindOneByTermId(ctx context.Context, termId int64) (*GameTermId, error) {
	var resp GameTermId
	query := fmt.Sprintf("select %s from %s where `term_id` = ? limit 1", gameTermIdRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, termId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameTermIdModel) Insert(ctx context.Context, data *GameTermId) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, gameTermIdRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermId, data.GameTermId)
	return ret, err
}

func (m *defaultGameTermIdModel) Update(ctx context.Context, newData *GameTermId) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameTermIdRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ChannelId, newData.TermId, newData.GameTermId, newData.Id)
	return err
}

func (m *defaultGameTermIdModel) tableName() string {
	return m.table
}
