// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameChannelMappingFieldNames          = builder.RawFieldNames(&GameChannelMapping{})
	gameChannelMappingRows                = strings.Join(gameChannelMappingFieldNames, ",")
	gameChannelMappingRowsExpectAutoSet   = strings.Join(stringx.Remove(gameChannelMappingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameChannelMappingRowsWithPlaceHolder = strings.Join(stringx.Remove(gameChannelMappingFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameChannelMappingModel interface {
		Insert(ctx context.Context, data *GameChannelMapping) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameChannelMapping, error)
		FindOneByClientIdApisysGameId(ctx context.Context, clientId int64, apisysGameId int64) (*GameChannelMapping, error)
		FindOneByApisysGameId(ctx context.Context, apisysGameId int64) (*GameChannelMapping, error)
		Update(ctx context.Context, data *GameChannelMapping) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameChannelMappingModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameChannelMapping struct {
		Id           int64     `db:"id"`             // 主键ID
		ClientId     int64     `db:"client_id"`      // 代理商ID
		ChannelId    string    `db:"channel_id"`     // 游戏ID
		ApisysGameId int64     `db:"apisys_game_id"` // apisys游戏ID
		CreateTime   time.Time `db:"create_time"`    // 创建时间
		UpdateTime   time.Time `db:"update_time"`    // 更新时间
	}
)

func newGameChannelMappingModel(conn sqlx.SqlConn) *defaultGameChannelMappingModel {
	return &defaultGameChannelMappingModel{
		conn:  conn,
		table: "`game_channel_mapping`",
	}
}

func (m *defaultGameChannelMappingModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameChannelMappingModel) FindOne(ctx context.Context, id int64) (*GameChannelMapping, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameChannelMappingRows, m.table)
	var resp GameChannelMapping
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameChannelMappingModel) FindOneByClientIdApisysGameId(ctx context.Context, clientId int64, apisysGameId int64) (*GameChannelMapping, error) {
	var resp GameChannelMapping
	query := fmt.Sprintf("select %s from %s where `client_id` = ? and `apisys_game_id` = ? limit 1", gameChannelMappingRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, clientId, apisysGameId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameChannelMappingModel) FindOneByApisysGameId(ctx context.Context, apisysGameId int64) (*GameChannelMapping, error) {
	var resp GameChannelMapping
	query := fmt.Sprintf("select %s from %s where `apisys_game_id` = ? limit 1", gameChannelMappingRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, apisysGameId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameChannelMappingModel) Insert(ctx context.Context, data *GameChannelMapping) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, gameChannelMappingRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.ChannelId, data.ApisysGameId)
	return ret, err
}

func (m *defaultGameChannelMappingModel) Update(ctx context.Context, newData *GameChannelMapping) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameChannelMappingRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ClientId, newData.ChannelId, newData.ApisysGameId, newData.Id)
	return err
}

func (m *defaultGameChannelMappingModel) tableName() string {
	return m.table
}
