// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameBonusPoolsCtrlLogFieldNames          = builder.RawFieldNames(&GameBonusPoolsCtrlLog{})
	gameBonusPoolsCtrlLogRows                = strings.Join(gameBonusPoolsCtrlLogFieldNames, ",")
	gameBonusPoolsCtrlLogRowsExpectAutoSet   = strings.Join(stringx.Remove(gameBonusPoolsCtrlLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameBonusPoolsCtrlLogRowsWithPlaceHolder = strings.Join(stringx.Remove(gameBonusPoolsCtrlLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameBonusPoolsCtrlLogModel interface {
		Insert(ctx context.Context, data *GameBonusPoolsCtrlLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameBonusPoolsCtrlLog, error)
		Update(ctx context.Context, data *GameBonusPoolsCtrlLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameBonusPoolsCtrlLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameBonusPoolsCtrlLog struct {
		Id          int64     `db:"id"`
		ClientId    int64     `db:"client_id"`     // 渠道id
		UserId      int64     `db:"user_id"`       // 此操作管理员的uid
		InPoolsAmt  int64     `db:"in_pools_amt"`  // 转入调控池金额 （*10000）
		OutPoolsAmt int64     `db:"out_pools_amt"` // 调控池转出金额 （*10000）
		CreateTime  time.Time `db:"create_time"`   // 创建时间
	}
)

func newGameBonusPoolsCtrlLogModel(conn sqlx.SqlConn) *defaultGameBonusPoolsCtrlLogModel {
	return &defaultGameBonusPoolsCtrlLogModel{
		conn:  conn,
		table: "`game_bonus_pools_ctrl_log`",
	}
}

func (m *defaultGameBonusPoolsCtrlLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameBonusPoolsCtrlLogModel) FindOne(ctx context.Context, id int64) (*GameBonusPoolsCtrlLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameBonusPoolsCtrlLogRows, m.table)
	var resp GameBonusPoolsCtrlLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameBonusPoolsCtrlLogModel) Insert(ctx context.Context, data *GameBonusPoolsCtrlLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, gameBonusPoolsCtrlLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.InPoolsAmt, data.OutPoolsAmt)
	return ret, err
}

func (m *defaultGameBonusPoolsCtrlLogModel) Update(ctx context.Context, data *GameBonusPoolsCtrlLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameBonusPoolsCtrlLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.InPoolsAmt, data.OutPoolsAmt, data.Id)
	return err
}

func (m *defaultGameBonusPoolsCtrlLogModel) tableName() string {
	return m.table
}
