// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gameCfgLogFieldNames          = builder.RawFieldNames(&GameCfgLog{})
	gameCfgLogRows                = strings.Join(gameCfgLogFieldNames, ",")
	gameCfgLogRowsExpectAutoSet   = strings.Join(stringx.Remove(gameCfgLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gameCfgLogRowsWithPlaceHolder = strings.Join(stringx.Remove(gameCfgLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gameCfgLogModel interface {
		Insert(ctx context.Context, data *GameCfgLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GameCfgLog, error)
		Update(ctx context.Context, data *GameCfgLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGameCfgLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GameCfgLog struct {
		Id              int64     `db:"id"`
		ClientId        int64     `db:"client_id"`         // 渠道id
		UserId          int64     `db:"user_id"`           // 调整人uid
		Rake            int64     `db:"rake"`              // 抽水率（*10,000）
		CtrlTriggerRate int64     `db:"ctrl_trigger_rate"` // 调控触发率（*10,000）
		CtrlPutRate     int64     `db:"ctrl_put_rate"`     // 调控池输出率（*10,000）
		CreateTime      time.Time `db:"create_time"`       // 创建时间
	}
)

func newGameCfgLogModel(conn sqlx.SqlConn) *defaultGameCfgLogModel {
	return &defaultGameCfgLogModel{
		conn:  conn,
		table: "`game_cfg_log`",
	}
}

func (m *defaultGameCfgLogModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGameCfgLogModel) FindOne(ctx context.Context, id int64) (*GameCfgLog, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gameCfgLogRows, m.table)
	var resp GameCfgLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGameCfgLogModel) Insert(ctx context.Context, data *GameCfgLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, gameCfgLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.Rake, data.CtrlTriggerRate, data.CtrlPutRate)
	return ret, err
}

func (m *defaultGameCfgLogModel) Update(ctx context.Context, data *GameCfgLog) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gameCfgLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.UserId, data.Rake, data.CtrlTriggerRate, data.CtrlPutRate, data.Id)
	return err
}

func (m *defaultGameCfgLogModel) tableName() string {
	return m.table
}
