// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	retryRefundTaskFieldNames          = builder.RawFieldNames(&RetryRefundTask{})
	retryRefundTaskRows                = strings.Join(retryRefundTaskFieldNames, ",")
	retryRefundTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(retryRefundTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	retryRefundTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(retryRefundTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	retryRefundTaskModel interface {
		Insert(ctx context.Context, data *RetryRefundTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RetryRefundTask, error)
		FindOneByBetId(ctx context.Context, betId int64) (*RetryRefundTask, error)
		Update(ctx context.Context, data *RetryRefundTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRetryRefundTaskModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RetryRefundTask struct {
		Id            int64     `db:"id"`
		BetId         int64     `db:"bet_id"`          // 注单id@bet.id
		Status        int64     `db:"status"`          // 重试状态 1=待重试 2=重试中 3=已兑现 4=需要人工干预
		RetryNum      int64     `db:"retry_num"`       // 已重试次数
		NextRetryTime int64     `db:"next_retry_time"` // 下次重试时间戳
		UpdateTime    time.Time `db:"update_time"`     // 更新时间
		CreateTime    time.Time `db:"create_time"`     // 创建时间
	}
)

func newRetryRefundTaskModel(conn sqlx.SqlConn) *defaultRetryRefundTaskModel {
	return &defaultRetryRefundTaskModel{
		conn:  conn,
		table: "`retry_refund_task`",
	}
}

func (m *defaultRetryRefundTaskModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRetryRefundTaskModel) FindOne(ctx context.Context, id int64) (*RetryRefundTask, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", retryRefundTaskRows, m.table)
	var resp RetryRefundTask
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRetryRefundTaskModel) FindOneByBetId(ctx context.Context, betId int64) (*RetryRefundTask, error) {
	var resp RetryRefundTask
	query := fmt.Sprintf("select %s from %s where `bet_id` = ? limit 1", retryRefundTaskRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, betId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRetryRefundTaskModel) Insert(ctx context.Context, data *RetryRefundTask) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, retryRefundTaskRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.BetId, data.Status, data.RetryNum, data.NextRetryTime)
	return ret, err
}

func (m *defaultRetryRefundTaskModel) Update(ctx context.Context, newData *RetryRefundTask) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, retryRefundTaskRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.BetId, newData.Status, newData.RetryNum, newData.NextRetryTime, newData.Id)
	return err
}

func (m *defaultRetryRefundTaskModel) tableName() string {
	return m.table
}
