// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	seedFileHashMgrFieldNames          = builder.RawFieldNames(&SeedFileHashMgr{})
	seedFileHashMgrRows                = strings.Join(seedFileHashMgrFieldNames, ",")
	seedFileHashMgrRowsExpectAutoSet   = strings.Join(stringx.Remove(seedFileHashMgrFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	seedFileHashMgrRowsWithPlaceHolder = strings.Join(stringx.Remove(seedFileHashMgrFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	seedFileHashMgrModel interface {
		Insert(ctx context.Context, data *SeedFileHashMgr) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SeedFileHashMgr, error)
		Update(ctx context.Context, data *SeedFileHashMgr) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSeedFileHashMgrModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SeedFileHashMgr struct {
		Id         int64  `db:"id"`          // 自增主键ID
		ChannelId  int64  `db:"channel_id"`  // 渠道ID
		TermStart  int64  `db:"term_start"`  // 起始期数ID
		TermEnd    int64  `db:"term_end"`    // 结束期数ID
		FileName   string `db:"file_name"`   // 文件名
		FileHash   string `db:"file_hash"`   // 文件哈希值
		FileUrl    string `db:"file_url"`    // 文件URL
		CreateTime int64  `db:"create_time"` // 创建时间(UNIX时间戳)
	}
)

func newSeedFileHashMgrModel(conn sqlx.SqlConn) *defaultSeedFileHashMgrModel {
	return &defaultSeedFileHashMgrModel{
		conn:  conn,
		table: "`seed_file_hash_mgr`",
	}
}

func (m *defaultSeedFileHashMgrModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSeedFileHashMgrModel) FindOne(ctx context.Context, id int64) (*SeedFileHashMgr, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", seedFileHashMgrRows, m.table)
	var resp SeedFileHashMgr
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSeedFileHashMgrModel) Insert(ctx context.Context, data *SeedFileHashMgr) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, seedFileHashMgrRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermStart, data.TermEnd, data.FileName, data.FileHash, data.FileUrl)
	return ret, err
}

func (m *defaultSeedFileHashMgrModel) Update(ctx context.Context, data *SeedFileHashMgr) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, seedFileHashMgrRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ChannelId, data.TermStart, data.TermEnd, data.FileName, data.FileHash, data.FileUrl, data.Id)
	return err
}

func (m *defaultSeedFileHashMgrModel) tableName() string {
	return m.table
}
