// Code generated by goctl. DO NOT EDIT.

package servermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPageConfigFieldNames          = builder.RawFieldNames(&UserPageConfig{})
	userPageConfigRows                = strings.Join(userPageConfigFieldNames, ",")
	userPageConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(userPageConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userPageConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(userPageConfigFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userPageConfigModel interface {
		Insert(ctx context.Context, data *UserPageConfig) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserPageConfig, error)
		Update(ctx context.Context, data *UserPageConfig) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserPageConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserPageConfig struct {
		Id         int64     `db:"id"`          // 配置ID
		UserId     int64     `db:"user_id"`     // 用户ID
		ConfigJson string    `db:"config_json"` // 页面配置JSON
		GameId     int64     `db:"game_id"`     // 游戏ID
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newUserPageConfigModel(conn sqlx.SqlConn) *defaultUserPageConfigModel {
	return &defaultUserPageConfigModel{
		conn:  conn,
		table: "`user_page_config`",
	}
}

func (m *defaultUserPageConfigModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserPageConfigModel) FindOne(ctx context.Context, id int64) (*UserPageConfig, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userPageConfigRows, m.table)
	var resp UserPageConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPageConfigModel) Insert(ctx context.Context, data *UserPageConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userPageConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConfigJson, data.GameId)
	return ret, err
}

func (m *defaultUserPageConfigModel) Update(ctx context.Context, data *UserPageConfig) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userPageConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ConfigJson, data.GameId, data.Id)
	return err
}

func (m *defaultUserPageConfigModel) tableName() string {
	return m.table
}
